name: Prometheus

on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 10 * * *' # everyday at 10am

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Cache Docker layers
                uses: actions/cache@v2
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-prometheus-${{ github.sha }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-prometheus-
                        ${{ runner.os }}-buildx-
            -
                name: Login to DockerHub
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v1 
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v2
                with:
                    context: ./prometheus
                    file: ./prometheus/Dockerfile 
                    push: ${{ github.event_name != 'pull_request' }}
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache
                    tags: eteissonniere/substrate-prometheus:latest