on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 10 * * *' # everyday at 10am

jobs:
    build:
        strategy:
            matrix:
                include:
                    # Add your own details here, just duplicate one of the entries below.
                    # `binary` is the name of your binary as created by cargo
                    # `git` is your github repo URL (must be publicly accessible)
                    # `package` is the rust package to build that will produce your binary

                    -
                        binary: nodle-chain
                        git: https://github.com/NodleCode/chain
                        package: nodle-chain
                    -
                        binary: polkadot
                        git: https://github.com/paritytech/polkadot
                        package: polkadot

        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Login to DockerHub
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v1 
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v2
                with:
                    push: ${{ github.event_name != 'pull_request' }}
                    build-args: |
                        GIT_REPO=
                        PACKAGE_NAME=
                        BINARY_NAME=